name: Roselma Mendes
bio: 'Feminista negra e desenvolvedora @thoughtworks'
picture: 'assets/images/eu.jpg'

#url: http://sergiokopplin.github.io/indigo
permalink: /:title/

analytics: 'UA-MYANALYTICS'
disqus: roselma_mendes
#facebook: myfacebook
twitter: roselmamendes
instagram: roselmamendes
#linkedin: mylinkedin
#youtube: myyoutube
#spotify: myspotify
github: roselmamendes
email: roselma.mendes@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com
