title: Blog da Roselma
email: roselma.mendes@gmail.com
description: Um pouco de Feminismo Negro Tech e Tecnologia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roselmamendes
github_username:  roselmamendes

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - premonition
  - jektify

highlighter: pygments 
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
  
permalink: /:categories/:title/

sass:
  style: compact

jektify:
  enable: true
  open: true
  toggle:
    enable: true  
  spotify:
    user: roselmamendes
    text: See me no Spotify
  sass:
    jekyll: true
    other:
      dir: "css"   
  title:
    enable: false
    text: "Jektify"
  description:
    enable: false
    text: |
      Jekyll plugin to generate html snippets for embedding Spotify Musics.
      To listen to the full song, open your Spotify and start these musics.

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
