title: Blog da Roselma
email: roselma.mendes@gmail.com
description: Um pouco de Feminismo Negro Tech e Tecnologia
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: roselmamendes
github_username:  roselmamendes

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
permalink: /:categories/:title/

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
